### ISSUE TITLE
Embedding R Shiny App in ESRI StoryMaps

### ISSUE THREAD

**Issue by matthewsabinCadmus** [USEPA/r-shiny-cloud-gov-instructions#1]
Hi,

We (Cadmus -- EPA Consultant) are trying to embed an R Shiny App that we've created and pushed to cloud.gov (https://snowpack_draft_final.app.cloud.gov/) into an ESRI StoryMap Project. However the app is not showing up as an iframe, it will just show a link. Are there any permissions in cloud.gov that would prevent an R Shiny app from being embedded into a webpage?

-Matt

**Comment by elinork** [comment]
This turned out to be because R Shiny does not include an x-frame-options header and cloud.gov defaults to DENY.
We did not find a solution to this in R Shiny. However, we have a proxy in front of our R Shiny apps that was able to supply an ALLOWALL x-frames-option header.
